name: analysis_of_pv_live
channels:
  - conda-forge
dependencies:
  - python

  # Scientific Python
  - pandas
  - matplotlib
  - xarray
  - pyarrow

  # Filesystem utils
  - pathy
  - fsspec
  - gcsfs

  # Interactive data analysis
  - ipykernel
  - notebook # Required for running notebooks in VS Code

  - pip:
    - pvlive-api
